/**
 * Created by arik.blumin on 4/6/2016.
 */
/**
 * Created by Moshi on 12/25/2014.
 */
var D9 = D9 || {};
D9.Constants = {};

// IamSafe related constant
D9.Constants.IamSafe = {};

D9.Constants.IamSafe.mainName = 'IAM Safe';

D9.Constants.IamSafe.AccountState = {
  Enabled: "Enabled",
  Disabled: "Disabled"
};

D9.Constants.IamSafe.DeviceState = {
  Discovered: "Discovered",
  Active: "Active",
  Suspended: "Suspended"
};

D9.Constants.IamSafe.iamType = {
  Role: 'Role',
  User: 'User'
}
D9.Constants.IamSafe.iamState = {
  Attached: {
    name: "Attached",
    displayName: "Protected",
    iconClass:'fa fa-diamond color-success'
  },
  Restricted: {
    name: "Restricted",
    displayName: "Restricted",
    iconClass:'fa fa-lock color-seaweed'
  },
  Excluded: {
    name: "Excluded",
    displayName: "Not Protected",
    iconClass:''
  },
  Unattached: {
    name: "Unattached",
    displayName: "Not Protected",
    iconClass:'fa fa-unlock color-D9-alerted'
  }
};

D9.Constants.IamSafe.UserAccountState = {
  NotInvited: "Not Invited",
  Pending: "Pending",
  Active: "Active",
  Enabled: "Enabled",
  Disabled: "Disabled"
};

D9.Constants.IamSafe.AccountMode = {
  OptIn: "OptIn",
  Mandatory: "Mandatory"
};

D9.Constants.Urls = {
  cloudSecurityGroup: '/securitygroups#cloud_sg',
  dome9SecurityGroup: '/securitygroups#d9_sg'
};

D9.Constants.PermissionSource = {
  Direct: 'Direct'
};

//types constants
D9.Constants.Types = {};

D9.Constants.Types.Resource = {
  AwsAccount: 'AwsAccount',
  AwsRegion: 'AwsRegion',
  AwsVpc: 'AwsVpc',
  AwsSecurityGroup: 'AwsSecurityGroup',
  AwsInstance: 'AwsInstance',
  AwsElb: 'AwsElb',
  AwsRds: 'AwsRds'
};

D9.Constants.Types.SG = {
  Cloud: 0,
  Dome9: 1
};

D9.Constants.Types.Scope = {
  CIDR: 'CIDR',
  DNS: 'DNS',
  IPList: 'IPList',
  MagicIP: 'MagicIP',
  AWS: 'AWS'
};

D9.Constants.Types.PolicyType = {
  Inbound: 0,
  Outbound: 1
};

D9.Constants.Types.AWSCredential = {
  RoleBased: 'RoleBased',
  UserBased: 'UserBased'
};

D9.Constants.LoggingType = {
  All: 0,
  Client: 1,
  Server: 2
};

D9.Constants.Types.SecurityGroup = 'sg';
D9.Constants.Types.EmergencyPolicy = 'ep';

D9.Constants.Types.LicensePlan = {
  Normal: 0,
  Enterprise: 1
};

D9.Constants.Types.BillingProvider = {
  Dome9: 'Dome9',
  CloudFlare: 'CloudFlare',
  VPLS: 'VPLS',
  AppDirectIBM: 'AppDirect/IBM',
  AppDirectRackSpace: 'AppDirect/RACKSPACE',
  Newvem: 4
};

D9.Constants.Types.GroupDiscoveryBehaviour = {
  ReadOnly: 'ReadOnly',
  FullManage: 'FullManage',
  Reset: 'Reset'
};

D9.Constants.Types.PermissionAction = {
  Access: 'access',
  Manage: 'manage',
  View: 'view',
  Create: 'create'
};

// API constants
D9.Constants.API = {};

D9.Constants.API.CloudSecurityGroups = D9.Constants.API.CloudSecurityGroups || {};

D9.Constants.API.CloudSecurityGroups.ChangeType = {
  IP_LIST_REPLACE: 0,
  UPDATE_SG: 1
};

D9.Constants.Protocols = [
  {name: 'ALL', code: -1, portRange: false, icmp: false},
  {name: 'TCP', code: 6, portRange: true, icmp: false},
  {name: 'UDP', code: 17, portRange: true, icmp: false},
  {name: 'ICMP', code: 1, portRange: false, icmp: true},
  {name: 'HOPOPT', code: 0, portRange: false, icmp: false},
  {name: 'IGMP', code: 2, portRange: false, icmp: false},
  {name: 'GGP', code: 3, portRange: false, icmp: false},
  {name: 'IPV4', code: 4, portRange: false, icmp: false},
  {name: 'ST', code: 5, portRange: false, icmp: false},
  {name: 'CBT', code: 7, portRange: false, icmp: false},
  {name: 'EGP', code: 8, portRange: false, icmp: false},
  {name: 'IGP', code: 9, portRange: false, icmp: false},
  {name: 'BBN-RCC-MON', code: 10, portRange: false, icmp: false},
  {name: 'NVP-II', code: 11, portRange: false, icmp: false},
  {name: 'PUP', code: 12, portRange: false, icmp: false},
  {name: 'ARGUS', code: 13, portRange: false, icmp: false},
  {name: 'EMCON', code: 14, portRange: false, icmp: false},
  {name: 'XNET', code: 15, portRange: false, icmp: false},
  {name: 'CHAOS', code: 16, portRange: false, icmp: false},
  {name: 'MUX', code: 18, portRange: false, icmp: false},
  {name: 'DCN-MEAS', code: 19, portRange: false, icmp: false},
  {name: 'HMP', code: 20, portRange: false, icmp: false},
  {name: 'PRM', code: 21, portRange: false, icmp: false},
  {name: 'XNS-IDP', code: 22, portRange: false, icmp: false},
  {name: 'TRUNK-1', code: 23, portRange: false, icmp: false},
  {name: 'TRUNK-2', code: 24, portRange: false, icmp: false},
  {name: 'LEAF-1', code: 25, portRange: false, icmp: false},
  {name: 'LEAF-2', code: 26, portRange: false, icmp: false},
  {name: 'RDP', code: 27, portRange: false, icmp: false},
  {name: 'IRTP', code: 28, portRange: false, icmp: false},
  {name: 'ISO-TP4', code: 29, portRange: false, icmp: false},
  {name: 'NETBLT', code: 30, portRange: false, icmp: false},
  {name: 'MFE-NSP', code: 31, portRange: false, icmp: false},
  {name: 'MERIT-INP', code: 32, portRange: false, icmp: false},
  {name: 'DCCP', code: 33, portRange: false, icmp: false},
  {name: '3PC', code: 34, portRange: false, icmp: false},
  {name: 'IDPR', code: 35, portRange: false, icmp: false},
  {name: 'XTP', code: 36, portRange: false, icmp: false},
  {name: 'DDP', code: 37, portRange: false, icmp: false},
  {name: 'IDPR-CMTP', code: 38, portRange: false, icmp: false},
  {name: 'TP++', code: 39, portRange: false, icmp: false},
  {name: 'IL', code: 40, portRange: false, icmp: false},
  {name: 'IPV6', code: 41, portRange: false, icmp: false},
  {name: 'SDRP', code: 42, portRange: false, icmp: false},
  {name: 'IPV6-ROUTE', code: 43, portRange: false, icmp: false},
  {name: 'IPV6-FRAG', code: 44, portRange: false, icmp: false},
  {name: 'IDRP', code: 45, portRange: false, icmp: false},
  {name: 'RSVP', code: 46, portRange: false, icmp: false},
  {name: 'GRE', code: 47, portRange: false, icmp: false},
  {name: 'DSR', code: 48, portRange: false, icmp: false},
  {name: 'BNA', code: 49, portRange: false, icmp: false},
  {name: 'ESP', code: 50, portRange: false, icmp: false},
  {name: 'AH', code: 51, portRange: false, icmp: false},
  {name: 'I-NLSP', code: 52, portRange: false, icmp: false},
  {name: 'SWIPE', code: 53, portRange: false, icmp: false},
  {name: 'NARP', code: 54, portRange: false, icmp: false},
  {name: 'MOBILE', code: 55, portRange: false, icmp: false},
  {name: 'TLSP', code: 56, portRange: false, icmp: false},
  {name: 'SKIP', code: 57, portRange: false, icmp: false},
  {name: 'IPV6-ICMP', code: 58, portRange: false, icmp: false},
  {name: 'IPV6-NONXT', code: 59, portRange: false, icmp: false},
  {name: 'IPV6-OPTS', code: 60, portRange: false, icmp: false},
  {name: 'CFTP', code: 62, portRange: false, icmp: false},
  {name: 'SAT-EXPAK', code: 64, portRange: false, icmp: false},
  {name: 'KRYPTOLAN', code: 65, portRange: false, icmp: false},
  {name: 'RVD', code: 66, portRange: false, icmp: false},
  {name: 'IPPC', code: 67, portRange: false, icmp: false},
  {name: 'SAT-MON', code: 69, portRange: false, icmp: false},
  {name: 'VISA', code: 70, portRange: false, icmp: false},
  {name: 'IPCV', code: 71, portRange: false, icmp: false},
  {name: 'CPNX', code: 72, portRange: false, icmp: false},
  {name: 'CPHB', code: 73, portRange: false, icmp: false},
  {name: 'WSN', code: 74, portRange: false, icmp: false},
  {name: 'PVP', code: 75, portRange: false, icmp: false},
  {name: 'BR-SAT-MON', code: 76, portRange: false, icmp: false},
  {name: 'SUN-ND', code: 77, portRange: false, icmp: false},
  {name: 'WB-MON', code: 78, portRange: false, icmp: false},
  {name: 'WB-EXPAK', code: 79, portRange: false, icmp: false},
  {name: 'ISO-IP', code: 80, portRange: false, icmp: false},
  {name: 'VMTP', code: 81, portRange: false, icmp: false},
  {name: 'SECURE-VMTP', code: 82, portRange: false, icmp: false},
  {name: 'VINES', code: 83, portRange: false, icmp: false},
  {name: 'TTP', code: 84, portRange: false, icmp: false},
  {name: 'NSFNET-IGP', code: 85, portRange: false, icmp: false},
  {name: 'DGP', code: 86, portRange: false, icmp: false},
  {name: 'TCF', code: 87, portRange: false, icmp: false},
  {name: 'EIGRP', code: 88, portRange: false, icmp: false},
  {name: 'OSPFIGP', code: 89, portRange: false, icmp: false},
  {name: 'SPRITE-RPC', code: 90, portRange: false, icmp: false},
  {name: 'LARP', code: 91, portRange: false, icmp: false},
  {name: 'MTP', code: 92, portRange: false, icmp: false},
  {name: 'AX.25', code: 93, portRange: false, icmp: false},
  {name: 'IPIP', code: 94, portRange: false, icmp: false},
  {name: 'MICP', code: 95, portRange: false, icmp: false},
  {name: 'SCC-SP', code: 96, portRange: false, icmp: false},
  {name: 'ETHERIP', code: 97, portRange: false, icmp: false},
  {name: 'ENCAP', code: 98, portRange: false, icmp: false},
  {name: 'GMTP', code: 100, portRange: false, icmp: false},
  {name: 'IFMP', code: 101, portRange: false, icmp: false},
  {name: 'PNNI', code: 102, portRange: false, icmp: false},
  {name: 'PIM', code: 103, portRange: false, icmp: false},
  {name: 'ARIS', code: 104, portRange: false, icmp: false},
  {name: 'SCPS', code: 105, portRange: false, icmp: false},
  {name: 'QNX', code: 106, portRange: false, icmp: false},
  {name: 'A/N', code: 107, portRange: false, icmp: false},
  {name: 'IPCOMP', code: 108, portRange: false, icmp: false},
  {name: 'SNP', code: 109, portRange: false, icmp: false},
  {name: 'COMPAQ-PEER', code: 110, portRange: false, icmp: false},
  {name: 'IPX-IN-IP', code: 111, portRange: false, icmp: false},
  {name: 'VRRP', code: 112, portRange: false, icmp: false},
  {name: 'PGM', code: 113, portRange: false, icmp: false},
  {name: 'L2TP', code: 115, portRange: false, icmp: false},
  {name: 'DDX', code: 116, portRange: false, icmp: false},
  {name: 'IATP', code: 117, portRange: false, icmp: false},
  {name: 'STP', code: 118, portRange: false, icmp: false},
  {name: 'SRP', code: 119, portRange: false, icmp: false},
  {name: 'UTI', code: 120, portRange: false, icmp: false},
  {name: 'SMP', code: 121, portRange: false, icmp: false},
  {name: 'SM', code: 122, portRange: false, icmp: false},
  {name: 'PTP', code: 123, portRange: false, icmp: false},
  {name: 'ISIS OVER IPV4', code: 124, portRange: false, icmp: false},
  {name: 'FIRE', code: 125, portRange: false, icmp: false},
  {name: 'CRTP', code: 126, portRange: false, icmp: false},
  {name: 'CRUDP', code: 127, portRange: false, icmp: false},
  {name: 'SSCOPMCE', code: 128, portRange: false, icmp: false},
  {name: 'IPLT', code: 129, portRange: false, icmp: false},
  {name: 'SPS', code: 130, portRange: false, icmp: false},
  {name: 'PIPE', code: 131, portRange: false, icmp: false},
  {name: 'SCTP', code: 132, portRange: false, icmp: false},
  {name: 'FC', code: 133, portRange: false, icmp: false},
  {name: 'RSVP-E2E-IGNORE', code: 134, portRange: false, icmp: false},
  {name: 'MOBILITY HEADER', code: 135, portRange: false, icmp: false},
  {name: 'UDPLITE', code: 136, portRange: false, icmp: false},
  {name: 'MPLS-IN-IP', code: 137, portRange: false, icmp: false},
  {name: 'MANET', code: 138, portRange: false, icmp: false},
  {name: 'HIP', code: 139, portRange: false, icmp: false},
  {name: 'SHIM6', code: 140, portRange: false, icmp: false},
  {name: 'WESP', code: 141, portRange: false, icmp: false},
  {name: 'ROHC', code: 142, portRange: false, icmp: false}
];

D9.Constants.icmpTypes = [
  {name: 'All', code: 256},
  {name: 'Echo Reply', code: 0},
  {name: 'Destination Unreachable', code: 3},
  {name: 'Source Quench', code: 4},
  {name: 'Redirect Message', code: 5},
  {name: 'Alternate Host Address', code: 6},
  {name: 'Echo Request', code: 8},
  {name: 'Router Advertisement', code: 9},
  {name: 'Router Solicitation', code: 10},
  {name: 'Time Exceeded', code: 11},
  {name: 'Parameter Problem: Bad IP header', code: 12},
  {name: 'Timestamp', code: 13},
  {name: 'Timestamp Reply', code: 14},
  {name: 'Information Request', code: 15},
  {name: 'Information Reply', code: 16},
  {name: 'Address Mask Request', code: 17},
  {name: 'Address Mask Reply', code: 18},
  {name: 'Traceroute', code: 30},
  {name: 'Datagram Conversion Error', code: 31},
  {name: 'Mobile Host Redirect', code: 32},
  {name: 'Where Are You', code: 33},
  {name: 'Here I Am', code: 34},
  {name: 'Mobile Registration Request', code: 35},
  {name: 'Mobile Registration Reply', code: 36},
  {name: 'Domain Name Request', code: 37},
  {name: 'Domain Name Reply', code: 38},
  {name: 'SKIP Algorithm Discovery Protocol', code: 39},
  {name: 'Photuris, Security Failures', code: 40}
];

D9.Constants.Region = {
  us_east_1: 0,
  us_west_1: 1,
  eu_west_1: 2,
  ap_southeast_1: 3,
  ap_northeast_1: 4,
  us_west_2: 5,
  sa_east_1: 6,
  az_1_region_a_geo_1: 7,
  az_2_region_a_geo_1: 8,
  az_3_region_a_geo_1: 9,
  ap_southeast_2: 10,
  mellanox_region: 11,
  us_gov_west_1: 12,
  eu_central_1: 13,
  ap_northeast_2: 14
};

D9.Constants.RegionName = {
  us_east_1: 'N. Virginia',
  us_west_2: 'Oregon',
  us_west_1: 'N. California',
  eu_west_1: 'Ireland',
  eu_central_1: 'Frankfurt',
  ap_southeast_1: 'Singpore',
  ap_southeast_2: 'Sydney',
  ap_northeast_1: 'Tokyo',
  ap_northeast_2: 'Seoul',
  sa_east_1: 'São Paulo'
};

D9.Constants.magicIps = [
  {
    value: "cloudflare",
    name: "CloudFlare",
    description: "CloudFlare's proxy servers"
  },
  {
    value: "incapsula",
    name: "Incapsula",
    description: "Incapsula's proxy servers"
  },
  {
    value: "newrelic",
    name: "New Relic",
    description: "New Relic availability monitoring"
  },
  {
    value: "dome9",
    name: "Dome9 Service",
    description: "Dome9 servers"
  }
];



/**
 * This constant is the AWS Available services actions that can be used in the policy document
 * Follow this link to get the updated list: http://run.plnkr.co/plunks/6u8tlJXjis1XW2f3AZYZ/
 * Read this for further information:  https://github.com/Dome9/webapp/wiki/Aws-Policy-Generator
 * @type {*[]}
 */
D9.Constants.AwsServicesActions = [
  {
    "name": "API Gateway",
    "prefix": "execute-api",
    "actions": [
      "Invoke",
      "InvalidateCache"
    ]
  },
  {
    "name": "AppStream",
    "prefix": "appstream",
    "actions": [
      "CreateApplication",
      "CreateSession",
      "DeleteApplication",
      "GetApiRoot",
      "GetApplication",
      "GetApplications",
      "GetApplicationError",
      "GetApplicationErrors",
      "GetApplicationStatus",
      "GetSession",
      "GetSessions",
      "GetSessionStatus",
      "UpdateApplication",
      "UpdateApplicationState",
      "UpdateSessionState"
    ]
  },
  {
    "name": "Auto Scaling",
    "prefix": "autoscaling",
    "actions": [
      "AttachInstances",
      "CompleteLifecycleAction",
      "CreateAutoScalingGroup",
      "CreateLaunchConfiguration",
      "CreateOrUpdateTags",
      "DeleteAutoScalingGroup",
      "DeleteLaunchConfiguration",
      "DeleteLifecycleHook",
      "DeleteNotificationConfiguration",
      "DeletePolicy",
      "DeleteScheduledAction",
      "DeleteTags",
      "DescribeAccountLimits",
      "DescribeAdjustmentTypes",
      "DescribeAutoScalingGroups",
      "DescribeAutoScalingInstances",
      "DescribeAutoScalingNotificationTypes",
      "DescribeLaunchConfigurations",
      "DescribeLifecycleHookTypes",
      "DescribeLifecycleHooks",
      "DescribeMetricCollectionTypes",
      "DescribeNotificationConfigurations",
      "DescribePolicies",
      "DescribeScalingActivities",
      "DescribeScalingProcessTypes",
      "DescribeScheduledActions",
      "DescribeTags",
      "DescribeTerminationPolicyTypes",
      "DetachInstances",
      "DisableMetricsCollection",
      "EnableMetricsCollection",
      "EnterStandby",
      "ExecutePolicy",
      "ExitStandby",
      "PutLifecycleHook",
      "PutNotificationConfiguration",
      "PutScalingPolicy",
      "PutScheduledUpdateGroupAction",
      "RecordLifecycleActionHeartbeat",
      "ResumeProcesses",
      "SetDesiredCapacity",
      "SetInstanceHealth",
      "SetInstanceProtection",
      "SuspendProcesses",
      "TerminateInstanceInAutoScalingGroup",
      "UpdateAutoScalingGroup"
    ]
  },
  {
    "name": "Billing",
    "prefix": "aws-portal",
    "actions": [
      "ModifyAccount",
      "ModifyBilling",
      "ModifyPaymentMethods",
      "ViewAccount",
      "ViewBilling",
      "ViewBudget",
      "ViewPaymentMethods",
      "ViewUsage"
    ]
  },
  {
    "name": "Certificate Manager",
    "prefix": "acm",
    "actions": [
      "DeleteCertificate",
      "DescribeCertificate",
      "GetCertificate",
      "ListCertificates",
      "RequestCertificate",
      "ResendValidationEmail"
    ]
  },
  {
    "name": "CloudFormation",
    "prefix": "cloudformation",
    "actions": [
      "CancelUpdateStack",
      "CreateStack",
      "CreateUploadBucket",
      "DeleteStack",
      "DescribeAccountLimits",
      "DescribeStackEvents",
      "DescribeStackResource",
      "DescribeStackResources",
      "DescribeStacks",
      "EstimateTemplateCost",
      "GetStackPolicy",
      "GetTemplate",
      "GetTemplateSummary",
      "ListStackResources",
      "ListStacks",
      "PreviewStackUpdate",
      "SetStackPolicy",
      "SignalResource",
      "UpdateStack",
      "ValidateTemplate"
    ]
  },
  {
    "name": "CloudFront",
    "prefix": "cloudfront",
    "actions": [
      "CreateCloudFrontOriginAccessIdentity",
      "CreateDistribution",
      "CreateInvalidation",
      "CreateStreamingDistribution",
      "DeleteCloudFrontOriginAccessIdentity",
      "DeleteDistribution",
      "DeleteStreamingDistribution",
      "GetCloudFrontOriginAccessIdentity",
      "GetCloudFrontOriginAccessIdentityConfig",
      "GetDistribution",
      "GetDistributionConfig",
      "GetInvalidation",
      "GetStreamingDistribution",
      "GetStreamingDistributionConfig",
      "ListCloudFrontOriginAccessIdentities",
      "ListDistributions",
      "ListDistributionsByWebACLId",
      "ListInvalidations",
      "ListStreamingDistributions",
      "UpdateCloudFrontOriginAccessIdentity",
      "UpdateDistribution",
      "UpdateStreamingDistribution"
    ]
  },
  {
    "name": "CloudHSM",
    "prefix": "cloudhsm",
    "actions": [
      "CreateLunaClient",
      "CreateHapg",
      "CreateHsm",
      "DeleteLunaClient",
      "DeleteHapg",
      "DeleteHsm",
      "DescribeLunaClient",
      "DescribeHapg",
      "DescribeHsm",
      "GetConfig",
      "ListAvailableZones",
      "ListLunaClients",
      "ListHapgs",
      "ListHsms",
      "ModifyLunaClient",
      "ModifyHapg",
      "ModifyHsm"
    ]
  },
  {
    "name": "CloudSearch",
    "prefix": "cloudsearch",
    "actions": [
      "BuildSuggesters",
      "CreateDomain",
      "DefineAnalysisScheme",
      "DefineExpression",
      "DefineIndexField",
      "DefineIndexFields",
      "DefineSuggester",
      "DeleteAnalysisScheme",
      "DeleteDomain",
      "DeleteExpression",
      "DeleteIndexField",
      "DeleteSuggester",
      "DescribeAnalysisSchemes",
      "DescribeAvailabilityOptions",
      "DescribeDomains",
      "DescribeExpressions",
      "DescribeIndexFields",
      "DescribeScalingParameters",
      "DescribeServiceAccessPolicies",
      "DescribeSuggesters",
      "document",
      "IndexDocuments",
      "ListDomainNames",
      "search",
      "suggest",
      "UpdateAvailabilityOptions",
      "UpdateScalingParameters",
      "UpdateServiceAccessPolicies"
    ]
  },
  {
    "name": "CloudTrail",
    "prefix": "cloudtrail",
    "actions": [
      "CreateTrail",
      "DeleteTrail",
      "DescribeTrails",
      "GetTrailStatus",
      "LookupEvents",
      "StartLogging",
      "StopLogging",
      "UpdateTrail"
    ]
  },
  {
    "name": "CloudWatch",
    "prefix": "cloudwatch",
    "actions": [
      "DeleteAlarms",
      "DescribeAlarmHistory",
      "DescribeAlarms",
      "DescribeAlarmsForMetric",
      "DisableAlarmActions",
      "EnableAlarmActions",
      "GetMetricData",
      "GetMetricStatistics",
      "ListMetrics",
      "PutMetricAlarm",
      "PutMetricData",
      "SetAlarmState"
    ]
  },
  {
    "name": "CloudWatch Events",
    "prefix": "events",
    "actions": [
      "DeleteRule",
      "DescribeRule",
      "DisableRule",
      "EnableRule",
      "ListRuleNamesByTarget",
      "ListRules",
      "ListTargetsByRule",
      "PutEvents",
      "PutRule",
      "PutTargets",
      "RemoveTargets",
      "TestEventPattern"
    ]
  },
  {
    "name": "CloudWatch Logs",
    "prefix": "logs",
    "actions": [
      "CancelExportTask",
      "CreateExportTask",
      "CreateLogGroup",
      "CreateLogStream",
      "DeleteDestination",
      "DeleteLogGroup",
      "DeleteLogStream",
      "DeleteMetricFilter",
      "DeleteRetentionPolicy",
      "DeleteSubscriptionFilter",
      "DescribeDestinations",
      "DescribeExportTasks",
      "DescribeLogGroups",
      "DescribeLogStreams",
      "DescribeMetricFilters",
      "DescribeSubscriptionFilters",
      "FilterLogEvents",
      "GetLogEvents",
      "PutDestination",
      "PutDestinationPolicy",
      "PutLogEvents",
      "PutMetricFilter",
      "PutRetentionPolicy",
      "PutSubscriptionFilter",
      "TestMetricFilter"
    ]
  },
  {
    "name": "CodeCommit",
    "prefix": "codecommit",
    "actions": [
      "BatchGetRepositories",
      "CreateBranch",
      "CreateRepository",
      "DeleteRepository",
      "GetBlob",
      "GetBranch",
      "GetObjectIdentifier",
      "GetRepository",
      "GetTree",
      "GitPull",
      "GitPush",
      "ListBranches",
      "ListRepositories",
      "UpdateDefaultBranch",
      "UpdateRepositoryDescription",
      "UpdateRepositoryName"
    ]
  },
  {
    "name": "CodeDeploy",
    "prefix": "codedeploy",
    "actions": [
      "AddTagsToOnPremisesInstances",
      "BatchGetApplications",
      "BatchGetDeployments",
      "BatchGetOnPremisesInstances",
      "CreateApplication",
      "CreateDeployment",
      "CreateDeploymentConfig",
      "CreateDeploymentGroup",
      "DeleteApplication",
      "DeleteDeploymentConfig",
      "DeleteDeploymentGroup",
      "DeregisterOnPremisesInstance",
      "GetApplication",
      "GetApplicationRevision",
      "GetDeployment",
      "GetDeploymentConfig",
      "GetDeploymentGroup",
      "GetDeploymentInstance",
      "GetOnPremisesInstance",
      "ListApplicationRevisions",
      "ListApplications",
      "ListDeploymentConfigs",
      "ListDeploymentGroups",
      "ListDeploymentInstances",
      "ListDeployments",
      "ListOnPremisesInstances",
      "RegisterApplicationRevision",
      "RegisterOnPremisesInstance",
      "RemoveTagsFromOnPremisesInstances",
      "StopDeployment",
      "UpdateApplication",
      "UpdateDeploymentGroup"
    ]
  },
  {
    "name": "CodePipeline",
    "prefix": "codepipeline",
    "actions": [
      "AcknowledgeJob",
      "AcknowledgeThirdPartyJob",
      "CreateCustomActionType",
      "CreatePipeline",
      "DeleteCustomActionType",
      "DeletePipeline",
      "DisableStageTransition",
      "EnableStageTransition",
      "GetPipeline",
      "GetPipelineState",
      "GetThirdPartyJobDetails",
      "ListActionTypes",
      "ListPipelines",
      "PollForJobs",
      "PollForThirdPartyJobs",
      "PutActionRevision",
      "PutJobFailureResult",
      "PutJobSuccessResult",
      "PutThirdPartyJobFailureResult",
      "PutThirdPartyJobSuccessResult",
      "StartPipelineExecution",
      "UpdatePipeline"
    ]
  },
  {
    "name": "Cognito Identity",
    "prefix": "cognito-identity",
    "actions": [
      "CreateIdentityPool",
      "DeleteIdentityPool",
      "DeleteIdentities",
      "DescribeIdentity",
      "DescribeIdentityPool",
      "GetIdentityPoolRoles",
      "GetOpenIdTokenForDeveloperIdentity",
      "ListIdentities",
      "ListIdentityPools",
      "LookupDeveloperIdentity",
      "MergeDeveloperIdentities",
      "SetIdentityPoolRoles",
      "UnlinkDeveloperIdentity",
      "UpdateIdentityPool"
    ]
  },
  {
    "name": "Cognito Sync",
    "prefix": "cognito-sync",
    "actions": [
      "BulkPublish",
      "DeleteDataset",
      "DescribeDataset",
      "DescribeIdentityUsage",
      "DescribeIdentityPoolUsage",
      "GetBulkPublishDetails",
      "GetCognitoEvents",
      "GetIdentityPoolConfiguration",
      "ListDatasets",
      "ListIdentityPoolUsage",
      "ListRecords",
      "RegisterDevice",
      "SetCognitoEvents",
      "SetIdentityPoolConfiguration",
      "SubscribeToDataset",
      "UpdateRecords",
      "UnsubscribeFromDataset"
    ]
  },
  {
    "name": "Config",
    "prefix": "config",
    "actions": [
      "DeleteConfigRule",
      "DeleteDeliveryChannel",
      "DeliverConfigSnapshot",
      "DescribeComplianceByConfigRule",
      "DescribeComplianceByResource",
      "DescribeConfigRuleEvaluationStatus",
      "DescribeConfigRules",
      "DescribeConfigurationRecorderStatus",
      "DescribeConfigurationRecorders",
      "DescribeDeliveryChannelStatus",
      "DescribeDeliveryChannels",
      "GetComplianceDetailsByConfigRule",
      "GetComplianceDetailsByResource",
      "GetComplianceSummaryByConfigRule",
      "GetComplianceSummaryByResourceType",
      "GetResourceConfigHistory",
      "GetResources",
      "GetTagKeys",
      "ListDiscoveredResources",
      "PutConfigRule",
      "PutConfigurationRecorder",
      "PutDeliveryChannel",
      "PutEvaluations",
      "StartConfigurationRecorder",
      "StopConfigurationRecorder"
    ]
  },
  {
    "name": "Data Pipeline",
    "prefix": "datapipeline",
    "actions": [
      "ActivatePipeline",
      "AddTags",
      "CreatePipeline",
      "DeactivatePipeline",
      "DeletePipeline",
      "DescribeObjects",
      "DescribePipelines",
      "EvaluateExpression",
      "GetAccountLimits",
      "GetPipelineDefinition",
      "ListPipelines",
      "PollForTask",
      "PutAccountLimits",
      "PutPipelineDefinition",
      "QueryObjects",
      "RemoteTags",
      "ReportTaskProgress",
      "ReportTaskRunnerHeartbeat",
      "SetStatus",
      "SetTaskStatus",
      "ValidatePipelineDefinition"
    ]
  },
  {
    "name": "Database Migration Service",
    "prefix": "dms",
    "actions": [
      "CreateEndpoint",
      "CreateReplicationInstance",
      "CreateReplicationSubnetGroup",
      "CreateReplicationTask",
      "DeleteEndpoint",
      "DeleteReplicationInstance",
      "DeleteReplicationSubnetGroup",
      "DeleteReplicationTask",
      "DescribeAccountAttributes",
      "DescribeConnections",
      "DescribeEndpointTypes",
      "DescribeEndpoints",
      "DescribeOrderableReplicationInstances",
      "DescribeRefreshSchemasStatus",
      "DescribeReplicationInstances",
      "DescribeReplicationSubnetGroups",
      "DescribeReplicationTasks",
      "DescribeSchemas",
      "DescribeTableStatistics",
      "ModifyEndpoint",
      "ModifyReplicationInstance",
      "ModifyReplicationSubnetGroup",
      "RefreshSchemas",
      "StartReplicationTask",
      "StopReplicationTask",
      "TestConnection"
    ]
  },
  {
    "name": "Device Farm",
    "prefix": "devicefarm",
    "actions": [
      "CreateDevicePool",
      "CreateProject",
      "CreateUpload",
      "GetDevice",
      "GetDevicePool",
      "GetDevicePoolCompatibility",
      "GetJob",
      "GetProject",
      "GetRun",
      "GetSuite",
      "GetTest",
      "GetUpload",
      "ListArtifacts",
      "ListDevicePools",
      "ListDevices",
      "ListJobs",
      "ListProjects",
      "ListRuns",
      "ListSamples",
      "ListSuites",
      "ListTests",
      "ListUniqueProblems",
      "ListUploads",
      "ScheduleRun"
    ]
  },
  {
    "name": "Direct Connect",
    "prefix": "directconnect",
    "actions": [
      "AllocateConnectionOnInterconnect",
      "AllocatePrivateVirtualInterface",
      "AllocatePublicVirtualInterface",
      "ConfirmConnection",
      "ConfirmPrivateVirtualInterface",
      "ConfirmPublicVirtualInterface",
      "CreateConnection",
      "CreateInterconnect",
      "CreatePrivateVirtualInterface",
      "CreatePublicVirtualInterface",
      "DeleteConnection",
      "DeleteInterconnect",
      "DeleteVirtualInterface",
      "DescribeConnections",
      "DescribeConnectionsOnInterconnect",
      "DescribeInterconnects",
      "DescribeLocations",
      "DescribeVirtualGateways",
      "DescribeVirtualInterfaces"
    ]
  },
  {
    "name": "Directory Service",
    "prefix": "ds",
    "actions": [
      "CreateComputer",
      "CreateDirectory",
      "CreateSnapshot",
      "CheckAlias",
      "ConnectDirectory",
      "DeleteDirectory",
      "DeleteSnapshot",
      "DescribeDirectories",
      "DescribeSnapshots",
      "GetDirectoryLimits",
      "GetSnapshotLimits",
      "ListAuthorizedApplications",
      "RepairDirectory",
      "RestoreFromSnapshot",
      "UpdateDirectory"
    ]
  },
  {
    "name": "DynamoDB",
    "prefix": "dynamodb",
    "actions": [
      "BatchGetItem",
      "BatchWriteItem",
      "CreateTable",
      "DeleteItem",
      "DeleteTable",
      "DescribeReservedCapacity",
      "DescribeReservedCapacityOfferings",
      "DescribeStream",
      "DescribeTable",
      "GetItem",
      "GetRecords",
      "GetShardIterator",
      "ListStreams",
      "ListTables",
      "PurchaseReservedCapacityOfferings",
      "PutItem",
      "Query",
      "Scan",
      "UpdateItem",
      "UpdateTable"
    ]
  },
  {
    "name": "EC2",
    "prefix": "ec2",
    "actions": [
      "AcceptVpcPeeringConnection",
      "ActivateLicense",
      "AllocateAddress",
      "AssignPrivateIpAddresses",
      "AssociateAddress",
      "AssociateDhcpOptions",
      "AssociateRouteTable",
      "AttachClassicLinkVpc",
      "AttachInternetGateway",
      "AttachNetworkInterface",
      "AttachVolume",
      "AttachVpnGateway",
      "AuthorizeSecurityGroupEgress",
      "AuthorizeSecurityGroupIngress",
      "BundleInstance",
      "CancelBundleTask",
      "CancelConversionTask",
      "CancelExportTask",
      "CancelImportTask",
      "CancelReservedInstancesListing",
      "CancelSpotFleetRequests",
      "CancelSpotInstanceRequests",
      "ConfirmProductInstance",
      "CopyImage",
      "CopySnapshot",
      "CreateCustomerGateway",
      "CreateDhcpOptions",
      "CreateFlowLogs",
      "CreateImage",
      "CreateInstanceExportTask",
      "CreateInternetGateway",
      "CreateKeyPair",
      "CreateNatGateway",
      "CreateNetworkAcl",
      "CreateNetworkAclEntry",
      "CreateNetworkInterface",
      "CreatePlacementGroup",
      "CreateReservedInstancesListing",
      "CreateRoute",
      "CreateRouteTable",
      "CreateSecurityGroup",
      "CreateSnapshot",
      "CreateSpotDatafeedSubscription",
      "CreateSubnet",
      "CreateTags",
      "CreateVolume",
      "CreateVpc",
      "CreateVpcEndpoint",
      "CreateVpcPeeringConnection",
      "CreateVpnConnection",
      "CreateVpnConnectionRoute",
      "CreateVpnGateway",
      "DeactivateLicense",
      "DeleteCustomerGateway",
      "DeleteDhcpOptions",
      "DeleteFlowLogs",
      "DeleteInternetGateway",
      "DeleteKeyPair",
      "DeleteNatGateway",
      "DeleteNetworkAcl",
      "DeleteNetworkAclEntry",
      "DeleteNetworkInterface",
      "DeletePlacementGroup",
      "DeleteRoute",
      "DeleteRouteTable",
      "DeleteSecurityGroup",
      "DeleteSnapshot",
      "DeleteSpotDatafeedSubscription",
      "DeleteSubnet",
      "DeleteTags",
      "DeleteVolume",
      "DeleteVpc",
      "DeleteVpcEndpoints",
      "DeleteVpcPeeringConnection",
      "DeleteVpnConnection",
      "DeleteVpnConnectionRoute",
      "DeleteVpnGateway",
      "DeregisterImage",
      "DescribeAccountAttributes",
      "DescribeAddresses",
      "DescribeAvailabilityZones",
      "DescribeBundleTasks",
      "DescribeClassicLinkInstances",
      "DescribeConversionTasks",
      "DescribeCustomerGateways",
      "DescribeDhcpOptions",
      "DescribeExportTasks",
      "DescribeFlowLogs",
      "DescribeHosts",
      "DescribeImageAttribute",
      "DescribeImages",
      "DescribeImportImageTasks",
      "DescribeImportSnapshotTasks",
      "DescribeInstanceAttribute",
      "DescribeInstanceStatus",
      "DescribeInstances",
      "DescribeInternetGateways",
      "DescribeKeyPairs",
      "DescribeLicenses",
      "DescribeMovingAddresses",
      "DescribeNatGateways",
      "DescribeNetworkAcls",
      "DescribeNetworkInterfaceAttribute",
      "DescribeNetworkInterfaces",
      "DescribePlacementGroups",
      "DescribePrefixLists",
      "DescribeRegions",
      "DescribeReservedInstances",
      "DescribeReservedInstancesListings",
      "DescribeReservedInstancesModifications",
      "DescribeReservedInstancesOfferings",
      "DescribeRouteTables",
      "DescribeSecurityGroups",
      "DescribeSnapshotAttribute",
      "DescribeSnapshots",
      "DescribeSpotDatafeedSubscription",
      "DescribeSpotFleetInstances",
      "DescribeSpotFleetRequestHistory",
      "DescribeSpotFleetRequests",
      "DescribeSpotInstanceRequests",
      "DescribeSpotPriceHistory",
      "DescribeStaleSecurityGroups",
      "DescribeSubnets",
      "DescribeTags",
      "DescribeVolumeAttribute",
      "DescribeVolumeStatus",
      "DescribeVolumes",
      "DescribeVpcAttribute",
      "DescribeVpcClassicLink",
      "DescribeVpcEndpointServices",
      "DescribeVpcEndpoints",
      "DescribeVpcPeeringConnections",
      "DescribeVpcs",
      "DescribeVpnConnections",
      "DescribeVpnGateways",
      "DetachClassicLinkVpc",
      "DetachInternetGateway",
      "DetachNetworkInterface",
      "DetachVolume",
      "DetachVpnGateway",
      "DisableVgwRoutePropagation",
      "DisableVpcClassicLink",
      "DisassociateAddress",
      "DisassociateRouteTable",
      "EnableVgwRoutePropagation",
      "EnableVolumeIO",
      "EnableVpcClassicLink",
      "GetConsoleOutput",
      "GetPasswordData",
      "ImportImage",
      "ImportInstance",
      "ImportKeyPair",
      "ImportSnapshot",
      "ImportVolume",
      "ModifyHosts",
      "ModifyIdFormat",
      "ModifyImageAttribute",
      "ModifyInstanceAttribute",
      "ModifyInstancePlacement",
      "ModifyNetworkInterfaceAttribute",
      "ModifyReservedInstances",
      "ModifySnapshotAttribute",
      "ModifySpotFleetRequest",
      "ModifySubnetAttribute",
      "ModifyVolumeAttribute",
      "ModifyVpcAttribute",
      "ModifyVpcEndpoint",
      "ModifyVpcPeeringConnectionOptions",
      "MonitorInstances",
      "MoveAddressToVpc",
      "PurchaseReservedInstancesOffering",
      "RebootInstances",
      "RegisterImage",
      "RejectVpcPeeringConnection",
      "ReleaseAddress",
      "ReleaseHosts",
      "ReplaceNetworkAclAssociation",
      "ReplaceNetworkAclEntry",
      "ReplaceRoute",
      "ReplaceRouteTableAssociation",
      "ReportInstanceStatus",
      "RequestSpotFleet",
      "RequestSpotInstances",
      "ResetImageAttribute",
      "ResetInstanceAttribute",
      "ResetNetworkInterfaceAttribute",
      "ResetSnapshotAttribute",
      "RestoreAddressToClassic",
      "RevokeSecurityGroupEgress",
      "RevokeSecurityGroupIngress",
      "RunInstances",
      "StartInstances",
      "StopInstances",
      "TerminateInstances",
      "UnassignPrivateIpAddresses",
      "UnmonitorInstances"
    ]
  },
  {
    "name": "EC2 Container Registry",
    "prefix": "ecr",
    "actions": [
      "BatchCheckLayerAvailability",
      "BatchDeleteImage",
      "BatchGetImage",
      "CompleteLayerUpload",
      "CreateRepository",
      "DeleteRepository",
      "DeleteRepositoryPolicy",
      "DescribeRepositories",
      "GetAuthorizationToken",
      "GetDownloadUrlForLayer",
      "GetManifest",
      "GetRepositoryPolicy",
      "InitiateLayerUpload",
      "ListImages",
      "PutImage",
      "SetRepositoryPolicy",
      "UploadLayerPart"
    ]
  },
  {
    "name": "EC2 Container Service",
    "prefix": "ecs",
    "actions": [
      "CreateCluster",
      "CreateService",
      "DeleteCluster",
      "DeleteService",
      "DeregisterContainerInstance",
      "DeregisterTaskDefinition",
      "DescribeClusters",
      "DescribeContainerInstances",
      "DescribeServices",
      "DescribeTaskDefinition",
      "DescribeTasks",
      "DiscoverPollEndpoint",
      "ListClusters",
      "ListContainerInstances",
      "ListServices",
      "ListTaskDefinitionFamilies",
      "ListTaskDefinitions",
      "ListTasks",
      "Poll",
      "RegisterContainerInstance",
      "RegisterTaskDefinition",
      "RunTask",
      "StartTask",
      "StopTask",
      "StartTelemetrySession",
      "SubmitContainerStateChange",
      "SubmitTaskStateChange",
      "UpdateContainerAgent",
      "UpdateService"
    ]
  },
  {
    "name": "EC2 Spot Fleet",
    "prefix": "ec2",
    "actions": [
      "CancelSpotFleetRequests",
      "DescribeSpotFleetInstances",
      "DescribeSpotFleetRequests",
      "DescribeSpotFleetRequestHistory",
      "RequestSpotFleet"
    ]
  },
  {
    "name": "ElastiCache",
    "prefix": "elasticache",
    "actions": [
      "AuthorizeCacheSecurityGroupIngress",
      "CopySnapshot",
      "CreateCacheCluster",
      "CreateCacheParameterGroup",
      "CreateCacheSecurityGroup",
      "CreateCacheSubnetGroup",
      "CreateReplicationGroup",
      "CreateSnapshot",
      "DeleteCacheCluster",
      "DeleteCacheParameterGroup",
      "DeleteCacheSecurityGroup",
      "DeleteCacheSubnetGroup",
      "DeleteReplicationGroup",
      "DeleteSnapshot",
      "DescribeCacheClusters",
      "DescribeCacheEngineVersions",
      "DescribeCacheParameterGroups",
      "DescribeCacheParameters",
      "DescribeCacheSecurityGroups",
      "DescribeCacheSubnetGroups",
      "DescribeEngineDefaultParameters",
      "DescribeEvents",
      "DescribeReplicationGroups",
      "DescribeReservedCacheNodes",
      "DescribeReservedCacheNodesOfferings",
      "DescribeSnapshots",
      "ListTagsForResource",
      "ModifyCacheCluster",
      "ModifyCacheParameterGroup",
      "ModifyCacheSubnetGroup",
      "ModifyReplicationGroup",
      "PurchaseReservedCacheNodesOffering",
      "RebootCacheCluster",
      "ResetCacheParameterGroup",
      "RevokeCacheSecurityGroupIngress"
    ]
  },
  {
    "name": "Elastic Beanstalk",
    "prefix": "elasticbeanstalk",
    "actions": [
      "CheckDNSAvailability",
      "CreateApplication",
      "CreateApplicationVersion",
      "CreateConfigurationTemplate",
      "CreateEnvironment",
      "CreateStorageLocation",
      "DeleteApplication",
      "DeleteApplicationVersion",
      "DeleteConfigurationTemplate",
      "DeleteEnvironmentConfiguration",
      "DescribeApplicationVersions",
      "DescribeApplications",
      "DescribeConfigurationOptions",
      "DescribeConfigurationSettings",
      "DescribeEnvironmentHealth",
      "DescribeEnvironmentResources",
      "DescribeEnvironments",
      "DescribeEvents",
      "DescribeInstancesHealth",
      "ListAvailableSolutionStacks",
      "RebuildEnvironment",
      "RequestEnvironmentInfo",
      "RestartAppServer",
      "RetrieveEnvironmentInfo",
      "SwapEnvironmentCNAMEs",
      "TerminateEnvironment",
      "UpdateApplication",
      "UpdateApplicationVersion",
      "UpdateConfigurationTemplate",
      "UpdateEnvironment",
      "ValidateConfigurationSettings"
    ]
  },
  {
    "name": "Elastic File System",
    "prefix": "elasticfilesystem",
    "actions": [
      "CreateFileSystem",
      "CreateTags",
      "DescribeTags",
      "DeleteTags",
      "CreateMountTarget",
      "ModifyMountTargetSecurityGroups",
      "DescribeMountTargetSecurityGroups",
      "DescribeFileSystems",
      "DescribeMountTargets",
      "DeleteMountTarget",
      "DeleteFileSystem"
    ]
  },
  {
    "name": "Elastic Load Balancing",
    "prefix": "elasticloadbalancing",
    "actions": [
      "AddTags",
      "ApplySecurityGroupsToLoadBalancer",
      "AttachLoadBalancerToSubnets",
      "ConfigureHealthCheck",
      "CreateAppCookieStickinessPolicy",
      "CreateLBCookieStickinessPolicy",
      "CreateLoadBalancer",
      "CreateLoadBalancerListeners",
      "CreateLoadBalancerPolicy",
      "DeleteLoadBalancer",
      "DeleteLoadBalancerListeners",
      "DeleteLoadBalancerPolicy",
      "DeregisterInstancesFromLoadBalancer",
      "DescribeInstanceHealth",
      "DescribeLoadBalancerAttributes",
      "DescribeLoadBalancerPolicyTypes",
      "DescribeLoadBalancerPolicies",
      "DescribeLoadBalancers",
      "DescribeTags",
      "DetachLoadBalancerFromSubnets",
      "DisableAvailabilityZonesForLoadBalancer",
      "EnableAvailabilityZonesForLoadBalancer",
      "ModifyLoadBalancerAttributes",
      "RemoveTags",
      "RegisterInstancesWithLoadBalancer",
      "SetLoadBalancerListenerSSLCertificate",
      "SetLoadBalancerPoliciesForBackendServer",
      "SetLoadBalancerPoliciesOfListener"
    ]
  },
  {
    "name": "Elastic MapReduce",
    "prefix": "elasticmapreduce",
    "actions": [
      "AddInstanceGroups",
      "AddTags",
      "AddJobFlowSteps",
      "DescribeCluster",
      "DescribeJobFlows",
      "DescribeStep",
      "ListBootstrapActions",
      "ListClusters",
      "ListInstanceGroups",
      "ListInstances",
      "ListSteps",
      "ModifyInstanceGroups",
      "RemoveTags",
      "RunJobFlow",
      "SetTerminationProtection",
      "SetVisibleToAllUsers",
      "TerminateJobFlows"
    ]
  },
  {
    "name": "Elastic Transcoder",
    "prefix": "elastictranscoder",
    "actions": [
      "CancelJob",
      "CreateJob",
      "CreatePipeline",
      "CreatePreset",
      "DeletePipeline",
      "DeletePreset",
      "ListJobsByPipeline",
      "ListJobsByStatus",
      "ListPipelines",
      "ListPresets",
      "ReadJob",
      "ReadPipeline",
      "ReadPreset",
      "TestRole",
      "UpdatePipeline",
      "UpdatePipelineNotifications",
      "UpdatePipelineStatus"
    ]
  },
  {
    "name": "Elasticsearch Service",
    "prefix": "es",
    "actions": [
      "AddTags",
      "CreateElasticsearchDomain",
      "DeleteElasticsearchDomain",
      "DescribeElasticsearchDomain",
      "DescribeElasticsearchDomains",
      "DescribeElasticsearchDomainConfig",
      "ListDomainNames",
      "ListTags",
      "RemoveTags",
      "UpdateElasticsearchDomainConfig"
    ]
  },
  {
    "name": "GameLift",
    "prefix": "gamelift",
    "actions": [
      "CreateAlias",
      "CreateBuild",
      "CreateFleet",
      "CreateGameSession",
      "CreatePlayerSession",
      "CreatePlayerSessions",
      "DeleteAlias",
      "DeleteBuild",
      "DeleteFleet",
      "DescribeAlias",
      "DescribeBuild",
      "DescribeEC2InstanceLimits",
      "DescribeFleetAttributes",
      "DescribeFleetCapacity",
      "DescribeFleetEvents",
      "DescribeFleetPortSettings",
      "DescribeFleetUtilization",
      "DescribeGameSessions",
      "DescribePlayerSessions",
      "GetGameSessionLogUrl",
      "ListAliases",
      "ListBuilds",
      "ListFleets",
      "RequestUploadCredentials",
      "ResolveAlias",
      "UpdateAlias",
      "UpdateBuild",
      "UpdateFleetAttributes",
      "UpdateFleetCapacity",
      "UpdateFleetPortSettings",
      "UpdateGameSession"
    ]
  },
  {
    "name": "Glacier",
    "prefix": "glacier",
    "actions": [
      "AbortVaultLock",
      "AddTagsToVault",
      "AbortMultipartUpload",
      "CompleteMultipartUpload",
      "CompleteVaultLock",
      "CreateVault",
      "DeleteArchive",
      "DeleteVault",
      "DeleteVaultAccessPolicy",
      "DeleteVaultNotifications",
      "DescribeJob",
      "DescribeVault",
      "GetDataRetrievalPolicy",
      "GetJobOutput",
      "GetVaultAccessPolicy",
      "GetVaultLock",
      "GetVaultNotifications",
      "InitiateJob",
      "InitiateMultipartUpload",
      "InitiateVaultLock",
      "ListJobs",
      "ListMultipartUploads",
      "ListParts",
      "ListTagsForVault",
      "ListVaults",
      "RemoveTagsFromVault",
      "SetDataRetrievalPolicy",
      "SetVaultAccessPolicy",
      "SetVaultNotifications",
      "UploadArchive",
      "UploadMultipartPart"
    ]
  },
  {
    "name": "Identity and Access Management",
    "prefix": "iam",
    "actions": [
      "AddRoleToInstanceProfile",
      "AddUserToGroup",
      "AddClientIDToOpenIDConnectProvider",
      "AttachGroupPolicy",
      "AttachRolePolicy",
      "AttachUserPolicy",
      "ChangePassword",
      "CreateAccessKey",
      "CreateAccountAlias",
      "CreateGroup",
      "CreateInstanceProfile",
      "CreateLoginProfile",
      "CreateOpenIDConnectProvider",
      "CreatePolicy",
      "CreatePolicyVersion",
      "CreateRole",
      "CreateSAMLProvider",
      "CreateUser",
      "CreateVirtualMFADevice",
      "DeactivateMFADevice",
      "DeleteAccessKey",
      "DeleteAccountAlias",
      "DeleteAccountPasswordPolicy",
      "DeleteGroup",
      "DeleteGroupPolicy",
      "DeleteInstanceProfile",
      "DeleteLoginProfile",
      "DeleteOpenIDConnectProvider",
      "DeletePolicy",
      "DeletePolicyVersion",
      "DeleteRole",
      "DeleteRolePolicy",
      "DeleteSAMLProvider",
      "DeleteSSHPublicKey",
      "DeleteServerCertificate",
      "DeleteSigningCertificate",
      "DeleteUser",
      "DeleteUserPolicy",
      "DeleteVirtualMFADevice",
      "DetachGroupPolicy",
      "DetachRolePolicy",
      "DetachUserPolicy",
      "EnableMFADevice",
      "GenerateCredentialReport",
      "GenerateServiceLastAccessedDetails",
      "GetAccessKeyLastUsed",
      "GetAccountAuthorizationDetails",
      "GetAccountPasswordPolicy",
      "GetAccountSummary",
      "GetContextKeysForCustomPolicy",
      "GetContextKeysForPrincipalPolicy",
      "GetCredentialReport",
      "GetGroup",
      "GetGroupPolicy",
      "GetInstanceProfile",
      "GetLoginProfile",
      "GetOpenIDConnectProvider",
      "GetPolicy",
      "GetPolicyVersion",
      "GetRole",
      "GetRolePolicy",
      "GetSAMLProvider",
      "GetSSHPublicKey",
      "GetServerCertificate",
      "GetServiceLastAccessedDetails",
      "GetUser",
      "GetUserPolicy",
      "ListAccessKeys",
      "ListAccountAliases",
      "ListAttachedGroupPolicies",
      "ListAttachedRolePolicies",
      "ListAttachedUserPolicies",
      "ListEntitiesForPolicy",
      "ListGroupPolicies",
      "ListGroups",
      "ListGroupsForUser",
      "ListInstanceProfiles",
      "ListInstanceProfilesForRole",
      "ListMFADevices",
      "ListOpenIDConnectProviders",
      "ListPolicies",
      "ListPolicyVersions",
      "ListRolePolicies",
      "ListRoles",
      "ListSAMLProviders",
      "ListSSHPublicKeys",
      "ListServerCertificates",
      "ListSigningCertificates",
      "ListUserPolicies",
      "ListUsers",
      "ListVirtualMFADevices",
      "PassRole",
      "PutGroupPolicy",
      "PutRolePolicy",
      "PutUserPolicy",
      "RemoveClientIDFromOpenIDConnectProvider",
      "RemoveRoleFromInstanceProfile",
      "RemoveUserFromGroup",
      "ResyncMFADevice",
      "SetDefaultPolicyVersion",
      "SimulateCustomPolicy",
      "SimulatePrincipalPolicy",
      "UpdateAccessKey",
      "UpdateAccountPasswordPolicy",
      "UpdateAssumeRolePolicy",
      "UpdateGroup",
      "UpdateLoginProfile",
      "UpdateOpenIDConnectProviderThumbprint",
      "UpdateSAMLProvider",
      "UpdateSSHPublicKey",
      "UpdateServerCertificate",
      "UpdateSigningCertificate",
      "UpdateUser",
      "UploadSSHPublicKey",
      "UploadServerCertificate",
      "UploadSigningCertificate"
    ]
  },
  {
    "name": "Import Export",
    "prefix": "importexport",
    "actions": [
      "CreateJob",
      "UpdateJob",
      "CancelJob",
      "ListJobs",
      "GetStatus",
      "GetShippingLabel"
    ]
  },
  {
    "name": "Inspector",
    "prefix": "inspector",
    "actions": [
      "AddAttributesToFindings",
      "AttachAssessmentAndRulesPackage",
      "CreateApplication",
      "CreateAssessment",
      "CreateResourceGroup",
      "DeleteApplication",
      "DeleteAssessment",
      "DeleteRun",
      "DescribeApplication",
      "DescribeAssessment",
      "DescribeCrossAccountAccessRole",
      "DescribeFinding",
      "DescribeResourceGroup",
      "DescribeRulesPackage",
      "DescribeRun",
      "DetachAssessmentAndRulesPackage",
      "GetAssessmentTelemetry",
      "ListApplications",
      "ListAssessmentAgents",
      "ListAssessments",
      "ListAttachedAssessments",
      "ListAttachedRulesPackages",
      "ListFindings",
      "ListRulesPackages",
      "ListRuns",
      "ListTagsForResource",
      "LocalizeText",
      "PreviewAgentsForResourceGroup",
      "RegisterCrossAccountAccessRole",
      "RemoveAttributesFromFindings",
      "RetireRulesPackage",
      "RunAssessment",
      "SetTagsForResource",
      "StartDataCollection",
      "StopDataCollection",
      "UpdateApplication",
      "UpdateAssessment"
    ]
  },
  {
    "name": "IoT",
    "prefix": "iot",
    "actions": [
      "AcceptCertificateTransfer",
      "AttachPrincipalPolicy",
      "AttachThingPrincipal",
      "CancelCertificateTransfer",
      "Connect",
      "CreateCertificateFromCsr",
      "CreateKeysAndCertificate",
      "CreatePolicy",
      "CreatePolicyVersion",
      "CreateThing",
      "CreateTopicRule",
      "DeleteCertificate",
      "DeletePolicy",
      "DeletePolicyVersion",
      "DeleteThing",
      "DeleteThingShadow",
      "DeleteTopicRule",
      "DescribeCertificate",
      "DescribeEndpoint",
      "DescribeThing",
      "DetachPrincipalPolicy",
      "DetachThingPrincipal",
      "GetLoggingOptions",
      "GetPolicy",
      "GetPolicyVersion",
      "GetThingShadow",
      "GetTopicRule",
      "ListCertificates",
      "ListPolicies",
      "ListPolicyVersions",
      "ListPrincipalPolicies",
      "ListPrincipalThings",
      "ListThingPrincipals",
      "ListThings",
      "ListTopicRules",
      "Publish",
      "Receive",
      "RejectCertificateTransfer",
      "ReplaceTopicRule",
      "SetDefaultPolicyVersion",
      "SetLoggingOptions",
      "Subscribe",
      "TransferCertificate",
      "UpdateCertificate",
      "UpdateThing",
      "UpdateThingShadow"
    ]
  },
  {
    "name": "Key Management Service",
    "prefix": "kms",
    "actions": [
      "CreateAlias",
      "CreateGrant",
      "CreateKey",
      "Decrypt",
      "DeleteAlias",
      "DescribeKey",
      "DisableKey",
      "DisableKeyRotation",
      "EnableKey",
      "EnableKeyRotation",
      "Encrypt",
      "GenerateRandom",
      "GenerateDataKey",
      "GenerateDataKeyWithoutPlaintext",
      "GetKeyPolicy",
      "GetKeyRotationStatus",
      "ListAliases",
      "ListGrants",
      "ListKeyPolicies",
      "ListKeys",
      "PutKeyPolicy",
      "ReEncrypt*",
      "RetireGrant",
      "RevokeGrant",
      "UpdateAlias",
      "UpdateKeyDescription"
    ]
  },
  {
    "name": "Kinesis",
    "prefix": "kinesis",
    "actions": [
      "AddTagsToStream",
      "CreateStream",
      "DecreaseStreamRetentionPeriod",
      "DeleteStream",
      "DescribeStream",
      "GetShardIterator",
      "GetRecords",
      "IncreaseStreamRetentionPeriod",
      "ListStreams",
      "ListTagsForStream",
      "MergeShards",
      "PutRecord",
      "PutRecords",
      "RemoveTagsFromStream",
      "SplitShard"
    ]
  },
  {
    "name": "Kinesis Firehose",
    "prefix": "firehose",
    "actions": [
      "CreateDeliveryStream",
      "DeleteDeliveryStream",
      "DescribeDeliveryStream",
      "ListDeliveryStreams",
      "PutRecord",
      "PutRecordBatch",
      "UpdateDestination"
    ]
  },
  {
    "name": "Lambda",
    "prefix": "lambda",
    "actions": [
      "AddPermission",
      "CreateAlias",
      "CreateEventSourceMapping",
      "CreateFunction",
      "DeleteAlias",
      "DeleteEventSourceMapping",
      "DeleteFunction",
      "GetAlias",
      "GetEventSourceMapping",
      "GetFunction",
      "GetFunctionConfiguration",
      "GetPolicy",
      "InvokeAsync",
      "InvokeFunction",
      "ListAliases",
      "ListEventSourceMappings",
      "ListFunctions",
      "ListVersionsByFunction",
      "PublishVersion",
      "RemovePermission",
      "UpdateAlias",
      "UpdateEventSourceMapping",
      "UpdateFunctionCode",
      "UpdateFunctionConfiguration"
    ]
  },
  {
    "name": "Machine Learning",
    "prefix": "machinelearning",
    "actions": [
      "CreateBatchPrediction",
      "CreateDataSourceFromRDS",
      "CreateDataSourceFromRedshift",
      "CreateDataSourceFromS3",
      "CreateEvaluation",
      "CreateMLModel",
      "CreateRealtimeEndpoint",
      "DeleteBatchPrediction",
      "DeleteDataSource",
      "DeleteEvaluation",
      "DeleteMLModel",
      "DeleteRealtimeEndpoint",
      "DescribeBatchPredictions",
      "DescribeDataSources",
      "DescribeEvaluations",
      "DescribeMLModels",
      "GetBatchPrediction",
      "GetDataSource",
      "GetEvaluation",
      "GetMLModel",
      "Predict",
      "UpdateBatchPrediction",
      "UpdateDataSource",
      "UpdateEvaluation",
      "UpdateMLModel"
    ]
  },
  {
    "name": "Manage - Amazon API Gateway",
    "prefix": "apigateway",
    "actions": [
      "DELETE",
      "GET",
      "HEAD",
      "OPTIONS",
      "PATCH",
      "POST",
      "PUT"
    ]
  },
  {
    "name": "Marketplace",
    "prefix": "aws-marketplace",
    "actions": [
      "Subscribe",
      "Unsubscribe",
      "ViewSubscriptions"
    ]
  },
  {
    "name": "Marketplace Management Portal",
    "prefix": "aws-marketplace-management",
    "actions": [
      "uploadFiles",
      "viewMarketing",
      "viewReports",
      "viewSupport"
    ]
  },
  {
    "name": "Mechanical Turk",
    "prefix": "mechanicalturk",
    "actions": [
      "ApproveAssignment",
      "ApproveRejectedAssignment",
      "AssignQualification",
      "BlockWorker",
      "ChangeHITTypeOfHIT",
      "CreateHIT",
      "CreateQualificationType",
      "DisableHIT",
      "DisposeHIT",
      "DisposeQualificationType",
      "ExtendHIT",
      "ForceExpireHIT",
      "GetAccountBalance",
      "GetAssignment",
      "GetAssignmentsForHIT",
      "GetBlockedWorkers",
      "GetBonusPayments",
      "GetFileUploadURL",
      "GetHIT",
      "GetHITsForQualificationType",
      "GetQualificationRequests",
      "GetQualificationScore",
      "GetQualificationType",
      "GetQualificationsForQualificationType",
      "GetRequesterStatistic",
      "GetRequesterWorkerStatistic",
      "GetReviewResultsForHIT",
      "GetReviewableHITs",
      "GrantBonus",
      "GrantQualification",
      "NotifyWorkers",
      "RegisterHITType",
      "RejectAssignment",
      "RejectQualificationRequest",
      "RevokeQualification",
      "SearchHITs",
      "SearchQualificationTypes",
      "SendTestEventNotification",
      "SetHITAsReviewing",
      "SetHITTypeNotification",
      "UnblockWorker",
      "UpdateQualificationScore",
      "UpdateQualificationType"
    ]
  },
  {
    "name": "Mobile Analytics",
    "prefix": "mobileanalytics",
    "actions": [
      "PutEvents",
      "GetReports",
      "GetFinancialReports"
    ]
  },
  {
    "name": "Mobile Hub",
    "prefix": "mobilehub",
    "actions": [
      "CreateProject",
      "CreateServiceRole",
      "DeleteProject",
      "GenerateProjectParameters",
      "GetProject",
      "ListAvailableFeatures",
      "ListAvailableRegions",
      "ListProjects",
      "UpdateProject",
      "ValidateProject",
      "VerifyServiceRole"
    ]
  },
  {
    "name": "OpsWorks",
    "prefix": "opsworks",
    "actions": [
      "AssignVolume",
      "AssociateElasticIp",
      "AttachElasticLoadBalancer",
      "CloneStack",
      "CreateApp",
      "CreateDeployment",
      "CreateInstance",
      "CreateLayer",
      "CreateStack",
      "CreateUserProfile",
      "DeleteApp",
      "DeleteInstance",
      "DeleteLayer",
      "DeleteStack",
      "DeleteUserProfile",
      "DeregisterElasticIp",
      "DeregisterVolume",
      "DescribeApps",
      "DescribeCommands",
      "DescribeDeployments",
      "DescribeElasticIps",
      "DescribeElasticLoadBalancers",
      "DescribeInstances",
      "DescribeLayers",
      "DescribeLoadBasedAutoScaling",
      "DescribePermissions",
      "DescribeRaidArrays",
      "DescribeRdsDbInstances",
      "DescribeServiceErrors",
      "DescribeStacks",
      "DescribeTimeBasedAutoScaling",
      "DescribeUserProfiles",
      "DescribeVolumes",
      "DetachElasticLoadBalancer",
      "DisassociateElasticIp",
      "GetHostnameSuggestion",
      "RebootInstance",
      "RegisterElasticIp",
      "RegisterVolume",
      "SetLoadBasedAutoScaling",
      "SetPermission",
      "SetTimeBasedAutoScaling",
      "StartInstance",
      "StartStack",
      "StopInstance",
      "StopStack",
      "UnassignVolume",
      "UpdateApp",
      "UpdateElasticIp",
      "UpdateInstance",
      "UpdateLayer",
      "UpdateStack",
      "UpdateUserProfile",
      "UpdateVolume"
    ]
  },
  {
    "name": "RDS",
    "prefix": "rds",
    "actions": [
      "AddTagsToResource",
      "AddSourceIdentifierToSubscription",
      "ApplyPendingMaintenanceAction",
      "AuthorizeDBSecurityGroupIngress",
      "CopyDBClusterSnapshot",
      "CopyDBParameterGroup",
      "CopyDBSnapshot",
      "CopyOptionGroup",
      "CreateDBClusterParameterGroup",
      "CreateDBClusterSnapshot",
      "CreateDBCluster",
      "CreateDBInstance",
      "CreateDBInstanceReadReplica",
      "CreateDBParameterGroup",
      "CreateDBSecurityGroup",
      "CreateDBSnapshot",
      "CreateDBSubnetGroup",
      "CreateEventSubscription",
      "CreateOptionGroup",
      "DeleteDBClusterParameterGroup",
      "DeleteDBClusterSnapshot",
      "DeleteDBCluster",
      "DeleteDBInstance",
      "DeleteDBParameterGroup",
      "DeleteDBSecurityGroup",
      "DeleteDBSnapshot",
      "DeleteDBSubnetGroup",
      "DeleteEventSubscription",
      "DeleteOptionGroup",
      "DescribeAccountAttributes",
      "DescribeCertificates",
      "DescribeEngineDefaultClusterParameters",
      "DescribeEngineDefaultParameters",
      "DescribeDBClusterParameterGroups",
      "DescribeDBClusterParameters",
      "DescribeDBClusterSnapshots",
      "DescribeDBClusters",
      "DescribeDBInstances",
      "DescribeDBLogFiles",
      "DescribeDBParameterGroups",
      "DescribeDBParameters",
      "DescribeDBSecurityGroups",
      "DescribeDBSnapshotAttributes",
      "DescribeDBSnapshots",
      "DescribeDBEngineVersions",
      "DescribeDBSubnetGroups",
      "DescribeEventCategories",
      "DescribeEvents",
      "DescribeEventSubscriptions",
      "DescribeOptionGroups",
      "DescribeOptionGroupOptions",
      "DescribeOrderableDBInstanceOptions",
      "DescribePendingMaintenanceActions",
      "DescribeReservedDBInstances",
      "DescribeReservedDBInstancesOfferings",
      "DownloadDBLogFilePortion",
      "FailoverDBCluster",
      "ListTagsForResource",
      "ModifyDBClusterParameterGroup",
      "ModifyDBCluster",
      "ModifyDBInstance",
      "ModifyDBParameterGroup",
      "ModifyDBSnapshotAttribute",
      "ModifyDBSubnetGroup",
      "ModifyEventSubscription",
      "ModifyOptionGroup",
      "PromoteReadReplica",
      "PurchaseReservedDBInstancesOffering",
      "RebootDBInstance",
      "RemoveSourceIdentifierFromSubscription",
      "RemoveTagsFromResource",
      "RestoreDBClusterFromSnapshot",
      "RestoreDBClusterToPointInTime",
      "RestoreDBInstanceFromDBSnapshot",
      "RestoreDBInstanceToPointInTime",
      "ResetDBClusterParameterGroup",
      "ResetDBParameterGroup",
      "RevokeDBSecurityGroupIngress"
    ]
  },
  {
    "name": "Redshift",
    "prefix": "redshift",
    "actions": [
      "AuthorizeClusterSecurityGroupIngress",
      "AuthorizeSnapshotAccess",
      "CancelQuerySession",
      "CopyClusterSnapshot",
      "CreateCluster",
      "CreateClusterParameterGroup",
      "CreateClusterSecurityGroup",
      "CreateClusterSnapshot",
      "CreateClusterSubnetGroup",
      "CreateEventSubscription",
      "CreateHsmClientCertificate",
      "CreateHsmConfiguration",
      "CreateTags",
      "DeleteCluster",
      "DeleteClusterParameterGroup",
      "DeleteClusterSecurityGroup",
      "DeleteClusterSnapshot",
      "DeleteClusterSubnetGroup",
      "DeleteEventSubscription",
      "DeleteHsmClientCertificate",
      "DeleteHsmConfiguration",
      "DeleteTags",
      "DescribeClusterParameterGroups",
      "DescribeClusterParameters",
      "DescribeClusterSecurityGroups",
      "DescribeClusterSnapshots",
      "DescribeClusterSubnetGroups",
      "DescribeClusterVersions",
      "DescribeClusters",
      "DescribeDefaultClusterParameters",
      "DescribeEventCategories",
      "DescribeEventSubscriptions",
      "DescribeEvents",
      "DescribeHsmClientCertificates",
      "DescribeHsmConfigurations",
      "DescribeLoggingStatus",
      "DescribeOrderableClusterOptions",
      "DescribeReservedNodeOfferings",
      "DescribeReservedNodes",
      "DescribeResize",
      "DescribeTags",
      "DisableLogging",
      "DisableSnapshotCopy",
      "EnableLogging",
      "EnableSnapshotCopy",
      "ModifyCluster",
      "ModifyClusterParameterGroup",
      "ModifyClusterSubnetGroup",
      "ModifyEventSubscription",
      "ModifySnapshotCopyRetentionPeriod",
      "PurchaseReservedNodeOffering",
      "RebootCluster",
      "ResetClusterParameterGroup",
      "RestoreFromClusterSnapshot",
      "RevokeClusterSecurityGroupIngress",
      "RevokeSnapshotAccess",
      "RotateEncryptionKey",
      "ViewQueriesInConsole"
    ]
  },
  {
    "name": "Route 53",
    "prefix": "route53",
    "actions": [
      "AssociateVPCWithHostedZone",
      "ChangeResourceRecordSets",
      "ChangeTagsForResource",
      "CreateHealthCheck",
      "CreateHostedZone",
      "CreateReusableDelegationSet",
      "CreateTrafficPolicy",
      "CreateTrafficPolicyInstance",
      "CreateTrafficPolicyVersion",
      "DeleteHealthCheck",
      "DeleteHostedZone",
      "DeleteReusableDelegationSet",
      "DeleteTrafficPolicy",
      "DeleteTrafficPolicyInstance",
      "DisableDomainAutoRenew",
      "DisassociateVPCFromHostedZone",
      "EnableDomainAutoRenew",
      "GetChange",
      "GetCheckerIpRanges",
      "GetGeoLocation",
      "GetHealthCheck",
      "GetHealthCheckCount",
      "GetHealthCheckLastFailureReason",
      "GetHealthCheckStatus",
      "GetHostedZone",
      "GetHostedZoneCount",
      "GetReusableDelegationSet",
      "GetTrafficPolicy",
      "GetTrafficPolicyInstance",
      "GetTrafficPolicyInstanceCount",
      "ListGeoLocations",
      "ListHealthChecks",
      "ListHostedZones",
      "ListHostedZonesByName",
      "ListResourceRecordSets",
      "ListReusableDelegationSets",
      "ListTagsForResource",
      "ListTagsForResources",
      "ListTrafficPolicies",
      "ListTrafficPolicyInstances",
      "ListTrafficPolicyInstancesByHostedZone",
      "ListTrafficPolicyInstancesByPolicy",
      "ListTrafficPolicyVersions",
      "UpdateHealthCheck",
      "UpdateHostedZoneComment",
      "UpdateTrafficPolicyComment",
      "UpdateTrafficPolicyInstance"
    ]
  },
  {
    "name": "Route53 Domains",
    "prefix": "route53domains",
    "actions": [
      "CheckDomainAvailability",
      "DeleteDomain",
      "DeleteTagsForDomain",
      "DisableDomainTransferLock",
      "EnableDomainTransferLock",
      "GetDomainDetail",
      "GetOperationDetail",
      "ListDomains",
      "ListOperations",
      "ListTagsForDomain",
      "RegisterDomain",
      "RetrieveDomainAuthCode",
      "TransferDomain",
      "UpdateDomainContact",
      "UpdateDomainContactPrivacy",
      "UpdateDomainNameservers",
      "UpdateTagsForDomain"
    ]
  },
  {
    "name": "S3",
    "prefix": "s3",
    "actions": [
      "AbortMultipartUpload",
      "CreateBucket",
      "DeleteBucket",
      "DeleteBucketPolicy",
      "DeleteBucketWebsite",
      "DeleteObject",
      "DeleteObjectVersion",
      "GetBucketAcl",
      "GetBucketCORS",
      "GetBucketLocation",
      "GetBucketLogging",
      "GetBucketNotification",
      "GetBucketPolicy",
      "GetBucketRequestPayment",
      "GetBucketTagging",
      "GetBucketVersioning",
      "GetBucketWebsite",
      "GetLifecycleConfiguration",
      "GetObject",
      "GetObjectAcl",
      "GetObjectTorrent",
      "GetObjectVersion",
      "GetObjectVersionAcl",
      "GetObjectVersionTorrent",
      "ListAllMyBuckets",
      "ListBucket",
      "ListBucketMultipartUploads",
      "ListBucketVersions",
      "ListMultipartUploadParts",
      "PutBucketAcl",
      "PutBucketCORS",
      "PutBucketLogging",
      "PutBucketNotification",
      "PutBucketPolicy",
      "PutBucketRequestPayment",
      "PutBucketTagging",
      "PutBucketVersioning",
      "PutBucketWebsite",
      "PutLifecycleConfiguration",
      "PutObject",
      "PutObjectAcl",
      "PutObjectVersionAcl",
      "RestoreObject"
    ]
  },
  {
    "name": "SES",
    "prefix": "ses",
    "actions": [
      "CloneReceiptRuleSet",
      "CreateReceiptFilter",
      "CreateReceiptRule",
      "CreateReceiptRuleSet",
      "DeleteIdentity",
      "DeleteIdentityPolicy",
      "DeleteReceiptFilter",
      "DeleteReceiptRule",
      "DeleteReceiptRuleSet",
      "DeleteVerifiedEmailAddress",
      "DescribeActiveReceiptRuleSet",
      "DescribeReceiptRule",
      "DescribeReceiptRuleSet",
      "GetIdentityDkimAttributes",
      "GetIdentityNotificationAttributes",
      "GetIdentityPolicies",
      "GetIdentityVerificationAttributes",
      "GetSendQuota",
      "GetSendStatistics",
      "ListIdentities",
      "ListIdentityPolicies",
      "ListReceiptFilters",
      "ListReceiptRuleSets",
      "ListVerifiedEmailAddresses",
      "PutIdentityPolicy",
      "ReorderReceiptRuleSet",
      "SendBounce",
      "SendEmail",
      "SendRawEmail",
      "SetActiveReceiptRuleSet",
      "SetIdentityDkimEnabled",
      "SetIdentityNotificationTopic",
      "SetIdentityFeedbackForwardingEnabled",
      "SetReceiptRulePosition",
      "UpdateReceiptRule",
      "VerifyDomainDkim",
      "VerifyDomainIdentity",
      "VerifyEmailAddress",
      "VerifyEmailIdentity"
    ]
  },
  {
    "name": "SNS",
    "prefix": "sns",
    "actions": [
      "AddPermission",
      "ConfirmSubscription",
      "CreatePlatformApplication",
      "CreatePlatformEndpoint",
      "CreateTopic",
      "DeleteEndpoint",
      "DeletePlatformApplication",
      "DeleteTopic",
      "GetEndpointAttributes",
      "GetPlatformApplicationAttributes",
      "GetSubscriptionAttributes",
      "GetTopicAttributes",
      "ListEndpointsByPlatformApplication",
      "ListPlatformApplications",
      "ListSubscriptions",
      "ListSubscriptionsByTopic",
      "ListTopics",
      "Publish",
      "RemovePermission",
      "SetEndpointAttributes",
      "SetPlatformApplicationAttributes",
      "SetSubscriptionAttributes",
      "SetTopicAttributes",
      "Subscribe",
      "Unsubscribe"
    ]
  },
  {
    "name": "SQS",
    "prefix": "sqs",
    "actions": [
      "AddPermission",
      "ChangeMessageVisibility",
      "ChangeMessageVisibilityBatch",
      "CreateQueue",
      "DeleteMessage",
      "DeleteMessageBatch",
      "DeleteQueue",
      "GetQueueAttributes",
      "GetQueueUrl",
      "ListDeadLetterSourceQueues",
      "ListQueues",
      "PurgeQueue",
      "ReceiveMessage",
      "RemovePermission",
      "SendMessage",
      "SendMessageBatch",
      "SetQueueAttributes"
    ]
  },
  {
    "name": "Security Token Service",
    "prefix": "sts",
    "actions": [
      "AssumeRole",
      "AssumeRoleWithSAML",
      "AssumeRoleWithWebIdentity",
      "DecodeAuthorizationMessage",
      "GetFederationToken",
      "GetSessionToken"
    ]
  },
  {
    "name": "Simple Systems Manager",
    "prefix": "ssm",
    "actions": [
      "CreateAssociation",
      "CreateAssociationBatch",
      "CreateDocument",
      "DeleteAssociation",
      "DeleteDocument",
      "DescribeAssociation",
      "DescribeDocument",
      "GetDocument",
      "ListAssociations",
      "ListDocuments",
      "UpdateAssociationStatus"
    ]
  },
  {
    "name": "Simple Workflow Service",
    "prefix": "swf",
    "actions": [
      "CancelTimer",
      "CancelWorkflowExecution",
      "CompleteWorkflowExecution",
      "ContinueAsNewWorkflowExecution",
      "CountClosedWorkflowExecutions",
      "CountOpenWorkflowExecutions",
      "CountPendingActivityTasks",
      "CountPendingDecisionTasks",
      "DeprecateActivityType",
      "DeprecateDomain",
      "DeprecateWorkflowType",
      "DescribeActivityType",
      "DescribeDomain",
      "DescribeWorkflowExecution",
      "DescribeWorkflowType",
      "FailWorkflowExecution",
      "GetWorkflowExecutionHistory",
      "ListActivityTypes",
      "ListClosedWorkflowExecutions",
      "ListDomains",
      "ListOpenWorkflowExecutions",
      "ListWorkflowTypes",
      "PollForActivityTask",
      "PollForDecisionTask",
      "RecordActivityTaskHeartbeat",
      "RecordMarker",
      "RegisterActivityType",
      "RegisterDomain",
      "RegisterWorkflowType",
      "RequestCancelActivityTask",
      "RequestCancelExternalWorkflowExecution",
      "RequestCancelWorkflowExecution",
      "RespondActivityTaskCanceled",
      "RespondActivityTaskCompleted",
      "RespondActivityTaskFailed",
      "RespondDecisionTaskCompleted",
      "ScheduleActivityTask",
      "SignalExternalWorkflowExecution",
      "SignalWorkflowExecution",
      "StartChildWorkflowExecution",
      "StartTimer",
      "StartWorkflowExecution",
      "TerminateWorkflowExecution"
    ]
  },
  {
    "name": "SimpleDB",
    "prefix": "sdb",
    "actions": [
      "BatchDeleteAttributes",
      "BatchPutAttributes",
      "CreateDomain",
      "DeleteAttributes",
      "DeleteDomain",
      "DomainMetadata",
      "GetAttributes",
      "ListDomains",
      "PutAttributes",
      "Select"
    ]
  },
  {
    "name": "Storage Gateway",
    "prefix": "storagegateway",
    "actions": [
      "ActivateGateway",
      "AddCache",
      "AddUploadBuffer",
      "AddWorkingStorage",
      "CancelArchival",
      "CancelRetrieval",
      "CreateCachediSCSIVolume",
      "CreateSnapshot",
      "CreateSnapshotFromVolumeRecoveryPoint",
      "CreateStorediSCSIVolume",
      "CreateTapes",
      "DeleteBandwidthRateLimit",
      "DeleteChapCredentials",
      "DeleteGateway",
      "DeleteSnapshotSchedule",
      "DeleteTape",
      "DeleteTapeArchive",
      "DeleteVolume",
      "DescribeBandwidthRateLimit",
      "DescribeCache",
      "DescribeCachediSCSIVolumes",
      "DescribeChapCredentials",
      "DescribeGatewayInformation",
      "DescribeMaintenanceStartTime",
      "DescribeSnapshotSchedule",
      "DescribeStorediSCSIVolumes",
      "DescribeTapeArchives",
      "DescribeTapeRecoveryPoints",
      "DescribeTapes",
      "DescribeUploadBuffer",
      "DescribeVTLDevices",
      "DescribeWorkingStorage",
      "DisableGateway",
      "ListGateways",
      "ListLocalDisks",
      "ListTagsForResource",
      "ListVolumeRecoveryPoints",
      "ListVolumes",
      "RetrieveTapeArchive",
      "RetrieveTapeRecoveryPoint",
      "ShutdownGateway",
      "StartGateway",
      "UpdateBandwidthRateLimit",
      "UpdateChapCredentials",
      "UpdateGatewayInformation",
      "UpdateGatewaySoftwareNow",
      "UpdateMaintenanceStartTime",
      "UpdateSnapshotSchedule"
    ]
  },
  {
    "name": "Trusted Advisor",
    "prefix": "trustedadvisor",
    "actions": [
      "DescribeCheckItems",
      "DescribeCheckRefreshStatuses",
      "DescribeCheckStatusHistoryChanges",
      "DescribeCheckSummaries",
      "DescribeNotificationPreferences",
      "ExcludeCheckItems",
      "IncludeCheckItems",
      "RefreshCheck",
      "UpdateNotificationPreferences"
    ]
  },
  {
    "name": "WAF",
    "prefix": "waf",
    "actions": [
      "CreateByteMatchSet",
      "CreateIPSet",
      "CreateRule",
      "CreateSqlInjectionMatchSet",
      "CreateWebACL",
      "DeleteByteMatchSet",
      "DeleteIPSet",
      "DeleteRule",
      "DeleteSqlInjectionMatchSet",
      "DeleteWebACL",
      "GetByteMatchSet",
      "GetChangeToken",
      "GetChangeTokenStatus",
      "GetIPSet",
      "GetRule",
      "GetSampledRequests",
      "GetSqlInjectionMatchSet",
      "GetWebACL",
      "ListByteMatchSets",
      "ListIPSets",
      "ListRules",
      "ListSqlInjectionMatchSets",
      "ListWebACLs",
      "UpdateByteMatchSet",
      "UpdateIPSet",
      "UpdateRule",
      "UpdateSqlInjectionMatchSet",
      "UpdateWebACL"
    ]
  },
  {
    "name": "WorkDocs",
    "prefix": "workdocs",
    "actions": [
      "ActivateUser",
      "AddUserToGroup",
      "CheckAlias",
      "CreateInstance",
      "DeactivateUser",
      "DeleteInstance",
      "DeregisterDirectory",
      "DescribeAvailableDirectories",
      "DescribeInstances",
      "RegisterDirectory",
      "RemoveUserFromGroup",
      "UpdateInstanceAlias"
    ]
  },
  {
    "name": "WorkMail",
    "prefix": "workmail",
    "actions": [
      "AddMembersToGroup",
      "CreateGroup",
      "CreateMailDomain",
      "CreateMailUser",
      "CreateOrganization",
      "DeleteOrganization",
      "DeleteMailDomain",
      "DeleteMobileDevice",
      "DescribeDirectories",
      "DescribeKmsKeys",
      "DescribeOrganizations",
      "DescribeMailDomains",
      "DescribeMailGroups",
      "DescribeMailUsers",
      "DisableMailGroups",
      "DisableMailUsers",
      "EnableMailDomain",
      "EnableMailUsers",
      "EnableMailGroups",
      "GetMailDomainDetails",
      "GetMailGroupDetails",
      "GetMailUserDetails",
      "GetMobileDeviceDetails",
      "GetMobileDevicesForUser",
      "GetMobilePolicyDetails",
      "ListMembersInMailGroup",
      "RemoveMembersFromGroup",
      "ResetUserPassword",
      "SearchMembers",
      "SetAdmin",
      "SetDefaultMailDomain",
      "SetMailGroupDetails",
      "SetMailUserDetails",
      "SetMobilePolicyDetails",
      "WipeMobileDevice"
    ]
  },
  {
    "name": "WorkSpaces",
    "prefix": "workspaces",
    "actions": [
      "CreateWorkspaces",
      "DescribeWorkspaceBundles",
      "DescribeWorkspaceDirectories",
      "DescribeWorkspaces",
      "RebootWorkspaces",
      "RebuildWorkspaces",
      "TerminateWorkspaces"
    ]
  },
  {
    "name": "WorkSpaces Application Manager",
    "prefix": "wam",
    "actions": [
      "AuthenticatePackager"
    ]
  }
];

D9.Constants.AwsServiceToCategory = {
  "API Gateway": "Application Services",
  "AppStream": "Application Services",
  "Auto Scaling": "Compute",
  "Billing": "Misc",
  "Certificate Manager": "Security & Identity",
  "CloudFormation": "Management Tools",
  "CloudFront": "Storage & Content Delivery",
  "CloudHSM": "Security & Identity",
  "CloudSearch": "Application Services",
  "CloudTrail": "Management Tools",
  "CloudWatch": "Management Tools",
  "CloudWatch Events": "Management Tools",
  "CloudWatch Logs": "Management Tools",
  "CodeCommit": "Developer Tools",
  "CodeDeploy": "Developer Tools",
  "CodePipeline": "Developer Tools",
  "Cognito Identity": "Mobile Services",
  "Cognito Sync": "Mobile Services",
  "Config": "Management Tools",
  "Data Pipeline": "Analytics",
  "Device Farm": "Mobile Services",
  "Direct Connect": "Networking",
  "Directory Service": "Security & Identity",
  "DynamoDB": "Database",
  "Database Migration Service": "Database",
  "EC2 Container Registry": "Compute",
  "GameLift": "Game Development",
  "Mechanical Turk": "Misc",
  "EC2": "Compute",
  "EC2 Container Service": "Compute",
  "EC2 Spot Fleet": "Compute",
  "ElastiCache": "Database",
  "Elastic Beanstalk": "Compute",
  "Elastic File System": "Storage & Content Delivery",
  "Elastic Load Balancing": "Compute",
  "Elastic MapReduce": "Analytics",
  "Elastic Transcoder": "Application Services",
  "Elasticsearch Service": "Analytics",
  "Glacier": "Storage & Content Delivery",
  "Identity and Access Management": "Security & Identity",
  "Import Export": "Storage & Content Delivery",
  "Inspector": "Security & Identity",
  "IoT": "Internet of Things",
  "Key Management Service": "Security & Identity",
  "Kinesis": "Analytics",
  "Kinesis Firehose": "Analytics",
  "Lambda": "Compute",
  "Machine Learning": "Analytics",
  "Manage - Amazon API Gateway": "Application Services",
  "Marketplace": "Misc",
  "Marketplace Management Portal": "Misc",
  "Mobile Analytics": "Mobile Services",
  "Mobile Hub": "Mobile Services",
  "OpsWorks": "Management Tools",
  "RDS": "Database",
  "Redshift": "Database",
  "Route 53": "Networking",
  "Route53 Domains": "Networking",
  "S3": "Storage & Content Delivery",
  "SES": "Application Services",
  "SNS": "Mobile Services",
  "SQS": "Application Services",
  "Security Token Service": "Security & Identity",
  "Simple Systems Manager": "Compute",
  "Simple Workflow Service": "Application Services",
  "SimpleDB": "Database",
  "Storage Gateway": "Storage & Content Delivery",
  "Trusted Advisor": "Management Tools",
  "WAF": "Security & Identity",
  "WorkDocs": "Enterprise Applications",
  "WorkMail": "Enterprise Applications",
  "WorkSpaces": "Enterprise Applications",
  "WorkSpaces Application Manager": "Enterprise Applications",
  "Zocalo": ""
};

module.exports ={
  D9:D9
};